# Generated by Django 2.2.4 on 2019-12-09 20:53

import awx.main.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_v370_projectupdate_job_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='webhook_payload',
            field=awx.main.fields.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='workflowjob',
            name='webhook_payload',
            field=awx.main.fields.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
