# Generated by Django 2.2.4 on 2019-12-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_v370_webhook_payload_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='acts_as_ci_check',
            field=models.BooleanField(default=False, help_text='Indicates that this template is used as a CI check.'),
        ),
        migrations.AddField(
            model_name='workflowjobtemplate',
            name='acts_as_ci_check',
            field=models.BooleanField(default=False, help_text='Indicates that this template is used as a CI check.'),
        ),
    ]
