---

- name: Create .build directory
  file:
    path: "{{ sources_dest }}"
    state: directory

- name: Render supervisor configs
  template:
    src: "{{ item }}.j2"
    dest: "{{ sources_dest }}/{{ item }}"
  with_items:
    - "nginx.conf"
    - "credentials.py"
    - "environment.sh"

- name: Copy Secret Key
  copy:
    content: "{{ secret_key }}"
    dest: "{{ sources_dest }}/SECRET_KEY"
    mode: 0600

- name: Render Docker-Compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ sources_dest }}/../{{ compose_name }}"
