---

- name: Create .build directory
  file:
    path: "{{ sources_dest }}"
    state: directory

- name: Render files
  template:
    src: "{{ item }}.j2"
    dest: "{{ sources_dest }}/{{ item }}"
  with_items:
    - "nginx.conf"
    - "credentials.py"
    - "environment.sh"

- name: Copy Secret Key
  copy:
    content: "{{ secret_key }}"
    dest: "{{ sources_dest }}/SECRET_KEY"
    mode: 0600

- name: Get OS info for sdb
  shell: |
    docker info | grep 'Operating System'
  register: os_info

- name: Get user UID
  shell: id -u
  register: current_user

- name: Set fact with user UID
  set_fact:
    user_id: "'{{ current_user.stdout }}'"

- name: Render Docker-Compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ sources_dest }}/{{ compose_name }}"
