---

- name: Stop AWX containers before migrating postgres so that the old postgres container does not get used
  docker_compose:
    project_src: "{{ old_docker_compose_dir }}"
    state: absent
  ignore_errors: true

- name: Create Data Volume
  docker_volume:
    name: awx_pg_data
    state: present

- debug:
    msg: "{{ postgres_data_dir }}"


- name: Migrate data from bind mount to new volume
  block:
  - name: Get full path of postgres data dir
    shell: "echo {{ postgres_data_dir }}"
    register: fq_postgres_data_dir
  # 
  # - name: Register temporary docker container
  #   set_fact:
  #     container_command: "docker run --rm -v '{{ fq_postgres_data_dir.stdout }}:/var/lib/postgresql' centos:8 bash -c "
  
  - name: Create temporary container
    docker_container:
      name: awx_tmps
      image: centos
      state: started
      recreate: true
      command: sh
      volumes:
        awx_pg_data:/data

  - name: Copy data into new volume
    become: true
    shell: |
      docker cp {{ fq_postgres_data_dir }}/12/data awx_tmp:/data

  - name: Clean up temporary container
    community.general.docker_container:
      name: awx_tmp
      state: absent
